Repository basf/MolPipeline, pull requests merged in 2024-09, with the labels that each got.

#73 72 make chemprop multiclass classification model
  .gitignore
  molpipeline/estimators/chemprop/component_wrapper.py
  molpipeline/estimators/chemprop/models.py
  test_extras/test_chemprop/chemprop_test_utils/constant_vars.py
  test_extras/test_chemprop/test_chemprop_pipeline.py
  test_extras/test_chemprop/test_models.py
  tests/test_data/multiclass_mock.tsv
Labels: type: enhancement

#69 68 makescaffoldgeneric set all carbons to wild card symbols to allow a substrcutre search
  molpipeline/mol2mol/scaffolds.py
  tests/test_elements/test_mol2mol/test_mol2scaffold.py
Labels: type: enhancement

#88 Add `--check-only` flag to isort
  .github/workflows/linting.yml
Labels: type: bug, type: maintenance

#92 add pylint.rc
  .github/workflows/linting.yml
  molpipeline/estimators/chemprop/component_wrapper.py
  molpipeline/mol2any/mol2path_fingerprint.py
Labels: type: maintenance

#82 81 postpredictionwrapper handle set params without wrapped estimator
  molpipeline/post_prediction.py
  tests/test_elements/test_post_prediction.py
Labels: type: bug
