Repository basf/MolPipeline, pull requests merged in 2024-07, with the labels that each got.

#39 fix rdkit and chemprop to last functioning versions
  requirements.txt
  requirements_chemprop.txt
Labels: type: refactoring or code improvement

#37 Fix: moltochemprop not compatible with chemprop 2.0.3
  molpipeline/estimators/chemprop/featurizer_wrapper/__init__.py
  molpipeline/estimators/chemprop/featurizer_wrapper/graph_wrapper.py
  molpipeline/mol2any/mol2chemprop.py
  requirements_chemprop.txt
  test_extras/test_chemprop/test_chemprop_pipeline.py
  test_extras/test_chemprop/test_models.py
  test_extras/test_chemprop/test_neural_fingerprint.py
Labels: type: maintenance

#30 Enhance github actions trigger
  .github/workflows/linting.yml
Labels: type: enhancement, status: doing

#46 Update tests to use FingerprintGenerator
  tests/test_estimators/test_similarity_transformation.py
Labels: type: maintenance

#49 Block logs for physchem descriptors
  molpipeline/mol2any/mol2rdkit_phys_chem.py
  pyproject.toml
Labels: type: maintenance

#35 Notebook changes
  notebooks/01_getting_started_with_molpipeline.ipynb
  notebooks/advanced_01_hyperopt_on_bbbp.ipynb
  notebooks/advanced_02_add_custom_pipeline_elements.ipynb
Labels: type: documentation

#53 45 tests use old fingerprint method (part 2)
  tests/utils/fingerprints.py
Labels: type: maintenance
